let input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

let grid = input.split("\n").map(line => line.split(""))
let count = 0

for (let i = 0; i < grid.length; i++) {
	for (let j = 0; j < grid[i].length; j++) {
		let cell = grid[i][j]

		if (cell === "S") {
			grid[i + 1][j] = "|"
		}

		if (cell === "|") {
			if (grid[i + 1]?.[j] === "^") {
				grid[i + 1][j - 1] = "|"
				grid[i + 1][j + 1] = "|"

				count++
			} else if (i !== grid.length - 1) {
				grid[i + 1][j] = "|"
			}
		}
	}
}
